---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: project-words
    path: "./configs/cspell.txt"
    addWords: true
dictionaries:
  - project-words
ignorePaths:
  - "duckling"
  - "utilities/shared/scrabble.txt"
  - "utilities/shared/time.py"
  - "utilities/shared/timezones.py"
  - "static"
  - "configs"
