networks:
  main:
    external: true
    name: main

services:
  bot:
    container_name: mipha
    extra_hosts:
      - "database:host-gateway"
    image: ghcr.io/abstractumbra/mipha:latest
    networks:
      main:
    restart: unless-stopped
    volumes:
      - ./configs/:/app/configs/:rw
      - ./logs/:/app/logs/:rw
      - ./static/:/app/static/:ro
      - ./extensions/private/:/app/extensions/private/:ro

  duckling:
    container_name: "duckling"
    image: ghcr.io/abstractumbra/duckling:latest
    networks:
      main:
        ipv4_address: 172.19.0.20
    restart: unless-stopped

  synth:
    container_name: synth-engine
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    restart: unless-stopped

version: "3"
