services:
  bot:
    container_name: mipha
    image: ghcr.io/abstractumbra/mipha:latest
    extra_hosts:
      - "database:host-gateway"
    restart: unless-stopped
    networks:
      default:
      main:
    volumes:
      - ./configs/:/app/configs/:rw
      - ./logs/:/app/logs/:rw
      - ./static/:/app/static/:rw
      - ./extensions/:/app/extensions/:ro
      - ./.git/:/app/.git/:ro
      - ./.safe-gitconfig:/root/.gitconfig:ro

  duckling:
    container_name: "duckling"
    image: ghcr.io/abstractumbra/duckling:latest
    restart: unless-stopped
    networks:
      default:

  synth:
    container_name: synth-engine
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    restart: unless-stopped
    networks:
      default:

networks:
  default:
    external: false
  main:
    external: true
