services:
  bot:
    container_name: mipha
    image: ghcr.io/abstractumbra/mipha:latest
    extra_hosts:
      - "database:host-gateway"
    restart: unless-stopped
    networks:
      default:
      access_pg:
    volumes:
      - ./configs/:/app/configs/:rw
      - ./logs/:/app/logs/:rw
      - ./static/:/app/static/:rw
      - ./extensions/:/app/extensions/:ro
      - ./.git/:/app/.git/:ro
      - ./.safe-gitconfig:/root/.gitconfig:ro

  duckling:
    container_name: mipha-duckling
    image: ghcr.io/abstractumbra/duckling:latest
    restart: unless-stopped
    networks:
      default:

  synth:
    container_name: mipha-synth
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    restart: unless-stopped
    networks:
      default:

  pyright:
    container_name: mipha-pyright
    image: ghcr.io/abstractumbra/pyright-api
    restart: unless-stopped
    networks:
      default:
    env_file:
      - .env

networks:
  default:
    external: false
  access_pg:
    external: true
