version: "3"

services:
  bot:
    container_name: mipha
    image: ghcr.io/abstractumbra/mipha:latest
    extra_hosts:
      - "database:host-gateway"
    restart: unless-stopped
    volumes:
      - ./configs/:/app/configs/:rw
      - ./logs/:/app/logs/:rw
      - ./static/:/app/static/:ro
      - ./extensions/:/app/extensions/:ro

  duckling:
    container_name: "duckling"
    image: ghcr.io/abstractumbra/duckling:latest
    restart: unless-stopped

  synth:
    container_name: synth-engine
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    restart: unless-stopped

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=foofuck
      - POSTGRES_USER=penumbra
      - POSTGRES_DB=mipha
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./schemas/:/docker-entrypoint-initdb.d/
    profiles:
      - db

volumes:
  pgdata:
