services:
  bot:
    container_name: mipha
    image: ghcr.io/abstractumbra/mipha:latest
    extra_hosts:
      - "database:host-gateway"
    restart: unless-stopped
    networks:
      default:
      main:
    volumes:
      - ./configs/:/app/configs/:rw
      - ./logs/:/app/logs/:rw
      - ./static/:/app/static/:rw
      - ./extensions/:/app/extensions/:ro
      - ./.git/:/app/.git/:ro
      - ./.safe-gitconfig:/root/.gitconfig:ro

  duckling:
    container_name: "duckling"
    image: ghcr.io/abstractumbra/duckling:latest
    restart: unless-stopped
    networks:
      default:

  synth:
    container_name: synth-engine
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    restart: unless-stopped
    networks:
      default:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=foofuck
      - POSTGRES_USER=penumbra
      - POSTGRES_DB=mipha
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./schemas/:/docker-entrypoint-initdb.d/
    profiles:
      - db
    networks:
      default:

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      default:
    volumes:
      - ./configs/redis.conf:/config/redis.conf:ro
    command: ["redis-server", "/config/redis.conf"]

volumes:
  pgdata:

networks:
  default:
    external: false
  main:
    external: true
