networks:
  main:
    external: true
    name: main

services:
  bot:
    container_name: mipha
    extra_hosts:
      - "database:host-gateway"
    image: ghcr.io/abstractumbra/mipha:latest
    networks:
      main:
    restart: unless-stopped
    volumes:
      - ./_bot_config.py:/app/_bot_config.py:ro
      - ./configs/:/app/configs/:rw
      - ./static/:/app/static/:ro
      - ./extensions/private/:/app/extensions/private/:ro

  duckling:
    container_name: "duckling"
    image: ghcr.io/abstractumbra/duckling:latest
    networks:
      main:
        ipv4_address: 172.19.0.20
    ports:
      - 127.0.0.1:7731:8000/tcp
    restart: unless-stopped

  synth:
    container_name: synth-engine
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "127.0.0.1:50021:50021"
    restart: unless-stopped

version: "3"
