name: Type Coverage and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.12', '3.x' ]

    name: "Type Coverage and Linting @ ${{ matrix.python-version }}"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "true"
          token: ${{ secrets.BUILD_GH_TOKEN }}

      - name: Setup PDM @ ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install deps @ ${{ matrix.python-version }}
        run: |
          pdm install --check --no-editable

      - name: Activate venv @ ${{ matrix.python-version }}
        run: |
          echo "$(pdm info --where)/.venv/bin" >> $GITHUB_PATH

      - name: "Run Pyright @ ${{ matrix.python-version }}"
        uses: jakebailey/pyright-action@v2
        with:
          warnings: false
          annotate: "${{ matrix.python-version != '3.x' }}"

      - name: Lint check
        uses: astral-sh/ruff-action@v2
        with:
          args: check .

      - name: Formatting check
        uses: chartboost/ruff-action@v1
        with:
          args: format --check
